export type DocumentationStatus="proposed"|"researching"|"documented"|"verified";
export type CommunityStatus="not-required"|"recommended"|"required"|"validated";
export type UsagePolicy="reference-only"|"faithful-reproduction"|"adaptation-with-attribution"|"community-approval-required"|"restricted";

export type HeritageEntry={
 id:string;name:string;system:string;people:string;geography:string;region:string;
 kind:string;meaning:string;documentationStatus:DocumentationStatus;communityStatus:CommunityStatus;
 usagePolicy:UsagePolicy;sourceLabel:string;sourceUrl:string;note?:string;
};

export const heritageEntries:HeritageEntry[]=[
{id:"AC-HER-001",name:"Mate Masie",system:"Adinkra",people:"Akan / Asante",geography:"Ghana · Côte d’Ivoire",region:"Afrique de l’Ouest",kind:"Idéogramme",meaning:"« What I hear, I keep » : sagesse et prudence.",documentationStatus:"documented",communityStatus:"recommended",usagePolicy:"faithful-reproduction",sourceLabel:"Smithsonian NMAfA",sourceUrl:"https://africa.si.edu/exhibitions/inscribing-meaning-writing-and-graphic-systems-africa-art"},
{id:"AC-HER-002",name:"Aban",system:"Adinkra",people:"Akan / Asante",geography:"Ghana",region:"Afrique de l’Ouest",kind:"Idéogramme",meaning:"Maison à deux étages / palais : force et autorité.",documentationStatus:"documented",communityStatus:"recommended",usagePolicy:"faithful-reproduction",sourceLabel:"Smithsonian NMAfA",sourceUrl:"https://africa.si.edu/exhibitions/inscribing-meaning-writing-and-graphic-systems-africa-art"},
{id:"AC-HER-003",name:"Compatibilité",system:"Nsibidi",people:"Ejagham et peuples voisins",geography:"Nigeria · Cameroun",region:"Golfe de Guinée",kind:"Système idéographique",meaning:"Symbole documenté de compatibilité.",documentationStatus:"documented",communityStatus:"required",usagePolicy:"community-approval-required",sourceLabel:"Smithsonian NMAfA",sourceUrl:"https://africa.si.edu/exhibitions/inscribing-meaning-writing-and-graphic-systems-africa-art",note:"Les niveaux profonds de connaissance nsibidi peuvent être restreints."},
{id:"AC-HER-004",name:"Lettre « lou »",system:"Bamum",people:"Bamum",geography:"Cameroun",region:"Afrique centrale",kind:"Syllabaire",meaning:"Caractère pour la syllabe « lou ».",documentationStatus:"documented",communityStatus:"recommended",usagePolicy:"reference-only",sourceLabel:"Smithsonian NMAfA",sourceUrl:"https://africa.si.edu/exhibitions/inscribing-meaning-writing-and-graphic-systems-africa-art"},
{id:"AC-HER-005",name:"Lettre « teh »",system:"Vai",people:"Vai / traditions mandé",geography:"Liberia · Sierra Leone",region:"Afrique de l’Ouest",kind:"Syllabaire",meaning:"Caractère pour la syllabe « teh ».",documentationStatus:"documented",communityStatus:"recommended",usagePolicy:"reference-only",sourceLabel:"Smithsonian NMAfA",sourceUrl:"https://africa.si.edu/exhibitions/inscribing-meaning-writing-and-graphic-systems-africa-art"},
{id:"AC-HER-006",name:"Son « eh »",system:"Tifinagh",people:"Touareg / Amazigh",geography:"Sahara · Afrique du Nord-Ouest",region:"Afrique du Nord / Sahara",kind:"Alphabet",meaning:"Lettre documentée pour le son « eh ».",documentationStatus:"documented",communityStatus:"recommended",usagePolicy:"reference-only",sourceLabel:"Smithsonian NMAfA",sourceUrl:"https://africa.si.edu/exhibitions/inscribing-meaning-writing-and-graphic-systems-africa-art"},
{id:"AC-HER-007",name:"Syllabe « gua »",system:"Ge’ez / Ethiopic",people:"Traditions éthiopiennes",geography:"Éthiopie · Corne de l’Afrique",region:"Corne de l’Afrique",kind:"Syllabaire",meaning:"Caractère documenté pour la syllabe « gua ».",documentationStatus:"documented",communityStatus:"recommended",usagePolicy:"reference-only",sourceLabel:"Smithsonian NMAfA",sourceUrl:"https://africa.si.edu/exhibitions/inscribing-meaning-writing-and-graphic-systems-africa-art"},
{id:"AC-HER-008",name:"Sona / Lusona",system:"Sona",people:"Lunda Cokwe et peuples voisins",geography:"Est de l’Angola",region:"Afrique centrale / australe",kind:"Dessin géométrique sur sable",meaning:"Transmission de croyances, pensées, histoires, connaissances et mémoire collective.",documentationStatus:"documented",communityStatus:"required",usagePolicy:"community-approval-required",sourceLabel:"UNESCO ICH",sourceUrl:"https://ich.unesco.org/fr/RL/sona-dessins-et-figures-geometriques-sur-le-sable-01994",note:"Certaines étapes avancées des rites d’initiation comportent des restrictions d’accès."},
];
export const heritagePipeline=["Proposé","À documenter","En vérification","Validé","Publié"] as const;
