import type { Metadata } from "next";
import { Braces, Clapperboard, Code2, LayoutTemplate, Palette, Users } from "lucide-react";
import { BrandActions } from "@/components/brand/brand-actions";
import { getBrandSettings } from "@/features/brand/settings";
import { HeritageExplorer } from "@/components/brand/heritage-explorer";
export const metadata:Metadata={title:"Brand Hub — AfroCodeurs",description:"Charte graphique et système de production officiel AfroCodeurs."};
const nav=[["Fondations","#fondations"],["Couleurs","#couleurs"],["Typographie","#typographie"],["Langage visuel","#langage"],["Métiers","#metiers"],["Webinars","#webinars"],["DO / DON'T","#rules"],["Production","#production"],["African Heritage","#heritage"]];
export default async function BrandPage(){const b=await getBrandSettings(); const palette=[["Gold 500",b.gold,"Signal · marque · CTA"],["Black 950",b.black,"Structure · texte · premium"],["Green 500",b.green,"Actif · contribution · succès"],["Ivory 50",b.ivory,"Fond clair"],["Night 1000",b.night,"Fond sombre"],["Stone 600",b.stone,"Texte secondaire"]]; return <div className="brand-page bg-[#FAFAF8] text-[#111111]">
<header className="border-b border-black/10 bg-[#111111] text-white"><div className="mx-auto max-w-7xl px-5 py-5 md:px-8"><div className="flex items-center justify-between gap-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-[#F5B800] text-lg font-black text-[#111111]">A</span><div><b>AfroCodeurs</b><p className="text-xs text-white/55">Brand Hub · v{b.version}</p></div></div><span className="hidden font-mono text-xs uppercase tracking-[.22em] text-[#F5B800] sm:block">Source de vérité</span></div></div></header>
<div className="mx-auto grid max-w-7xl md:grid-cols-[220px_minmax(0,1fr)]"><aside className="brand-sidebar border-r border-black/10 px-5 py-8 md:sticky md:top-0 md:h-screen md:px-6"><p className="mb-4 font-mono text-[10px] font-bold uppercase tracking-[.22em] text-black/45">Navigation</p><nav className="grid grid-cols-2 gap-1 text-sm md:grid-cols-1">{nav.map(([l,h])=><a key={h} href={h} className="rounded-md px-3 py-2 font-medium hover:bg-black/5">{l}</a>)}</nav><p className="mt-8 hidden border-t border-black/10 pt-6 text-xs leading-5 text-black/55 md:block">À transmettre avec chaque brief créatif ou technique.</p></aside>
<main className="min-w-0">
<section id="fondations" className="brand-section relative overflow-hidden border-b border-black/10 px-5 py-16 md:px-12 md:py-24"><div className="absolute right-0 top-0 h-full w-3 bg-[#F5B800]"/><p className="font-mono text-xs font-bold uppercase tracking-[.25em]">AfroCodeurs · Brand system</p><h1 className="mt-5 max-w-4xl text-5xl font-black leading-[.95] tracking-[-.05em] md:text-8xl">{b.tagline}</h1><p className="copy">{b.intro} Cette page est la référence commune du design, du motion, du produit et de la communication.</p><div className="mt-8"><BrandActions/></div><div className="mt-14 grid gap-px overflow-hidden rounded-xl border border-black/10 bg-black/10 sm:grid-cols-3">{[["SIGNAL","Un repère or identifiable"],["STRUCTURE","Grille, code, système"],["HUMAIN","Personnes, voix, réalités"]].map(([a,b])=><div key={a} className="bg-[#FAFAF8] p-6"><b className="text-xl">{a}</b><p className="mt-2 text-sm text-black/55">{b}</p></div>)}</div></section>
<section id="couleurs" className="brand-section border-b border-black/10 px-5 py-14 md:px-12"><Eyebrow icon={Palette}>01 · Couleurs</Eyebrow><Title>Une palette courte. Une reconnaissance forte.</Title><p className="copy">60 % neutres · 30 % noir · 10 % or. Le vert signale l’activité et la réussite ; il ne concurrence pas l’or comme couleur propriétaire.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{palette.map(([n,h,u])=><div key={h} className="overflow-hidden rounded-xl border border-black/10 bg-white"><div className="h-32" style={{background:h}}/><div className="p-4"><div className="flex justify-between gap-3"><b>{n}</b><code>{h}</code></div><p className="mt-1 text-xs text-black/50">{u}</p></div></div>)}</div></section>
<section id="typographie" className="brand-section border-b border-black/10 px-5 py-14 md:px-12"><Eyebrow icon={Braces}>02 · Typographie</Eyebrow><Title>Franche pour parler. Mono pour coder.</Title><div className="mt-8 grid gap-5 lg:grid-cols-2"><Card><p className="text-xs font-bold uppercase tracking-widest text-black/45">Display · Geist / Inter</p><p className="mt-6 text-5xl font-black leading-none tracking-[-.04em]">BUILD<br/>BEFORE<br/>CONSUME.</p></Card><Card><p className="font-mono text-xs font-bold uppercase tracking-widest text-black/45">Mono · Geist Mono</p><div className="mt-6 rounded-lg bg-[#111111] p-5 font-mono text-sm leading-7 text-[#F5B800]">problem → idea<br/>idea → code<br/>code → solution</div></Card></div></section>
<section id="langage" className="brand-section border-b border-black/10 bg-[#111111] px-5 py-14 text-white md:px-12"><Eyebrow icon={LayoutTemplate}>03 · Langage visuel</Eyebrow><Title>Afrique contemporaine. Pas décorative.</Title><p className="copy !text-white/60">{b.visualGuidance}</p><div className="mt-8 grid gap-4 md:grid-cols-3">{["Network Grid","Problem → Solution","Continental Nodes"].map((x,i)=><div key={x} className="min-h-44 rounded-xl border border-white/15 p-5"><span className="font-mono text-xs text-[#F5B800]">0{i+1}</span><div className="my-9 flex gap-4">{[1,2,3,4].map(n=><span key={n} className="size-3 rounded-full bg-[#F5B800]"/>)}</div><b>{x}</b></div>)}</div></section>
<section id="metiers" className="brand-section border-b border-black/10 px-5 py-14 md:px-12"><Eyebrow icon={Users}>04 · Une marque, plusieurs métiers</Eyebrow><Title>Chacun crée. Personne ne réinvente la marque.</Title><div className="mt-8 grid gap-4 md:grid-cols-2">{([[Palette,"Graphiste / DA",b.graphicGuidance],[Clapperboard,"Motion designer",b.motionGuidance],[Code2,"Développeur",b.devGuidance],[Users,"Social / Community",b.socialGuidance]] as const).map(([Icon,n,d])=><Card key={n}><Icon className="size-6"/><h3 className="mt-8 text-2xl font-black">{n}</h3><p className="mt-2 text-sm leading-6 text-black/55">{d}</p></Card>)}</div></section>
<section id="webinars" className="brand-section border-b border-black/10 px-5 py-14 md:px-12"><Eyebrow icon={Clapperboard}>05 · AfroCodeurs Webinars</Eyebrow><Title>Une série reconnaissable avant même de lire le titre.</Title><div className="mt-8 overflow-hidden rounded-2xl bg-[#111111] text-white md:grid md:grid-cols-[1.2fr_.8fr]"><div className="p-7 md:p-10"><p className="font-mono text-xs font-bold tracking-[.22em] text-[#F5B800]">{b.webinarLabel}</p><h3 className="mt-8 whitespace-pre-line text-4xl font-black leading-none md:text-6xl">{b.webinarTitle}</h3><div className="mt-14 border-t border-white/15 pt-5 text-sm text-white/60">{b.webinarMeta}</div></div><div className="grid min-h-72 place-items-center bg-[#F5B800] p-8 text-[#111111]"><div className="text-center"><div className="mx-auto grid size-28 place-items-center rounded-full border-4 border-[#111111] text-5xl font-black">01</div><p className="mt-5 font-mono text-xs font-bold">SIGNAL + STRUCTURE + HUMAIN</p></div></div></div><p className="mt-5 text-sm text-black/55">Annonce · speaker reveal · J-7/J-3 · live · replay · citation · carousel.</p></section>
<section id="rules" className="brand-section border-b border-black/10 px-5 py-14 md:px-12"><Eyebrow icon={Palette}>06 · DO / DON&apos;T</Eyebrow><Title>La cohérence vient aussi de ce qu’on refuse.</Title><div className="mt-8 grid gap-5 md:grid-cols-2"><Rule title="✓ DO" good items={["Une idée principale par support.","Or comme signal propriétaire.","Photos africaines crédibles et humaines.","Grilles et compositions franches.","Sources éditables + exports."]}/><Rule title="× DON'T" items={["Folklore africain générique.","Cyberpunk/glitch sans justification.","Jaunes approximatifs.","Déformer ou recolorer le logo.","Livrer seulement final_vrai2.jpg."]}/></div></section>
<section id="heritage" className="brand-section border-b border-black/10 px-5 py-14 md:px-12"><Eyebrow icon={LayoutTemplate}>08 · African Heritage</Eyebrow><Title>Documenter avant de réinterpréter.</Title><p className="copy">Un registre vivant des systèmes graphiques et traditions documentées du continent. Heritage n’est pas une banque décorative : chaque entrée conserve sa provenance, son sens attesté, sa source et ses règles d’usage.</p><HeritageExplorer/></section>
<section id="production" className="brand-section px-5 py-14 md:px-12"><Eyebrow icon={Code2}>07 · Production & handoff</Eyebrow><Title>Une création doit survivre à son créateur.</Title><div className="mt-8 rounded-2xl border border-black/10 bg-white p-6 md:p-8"><div className="grid gap-3 font-mono text-xs font-bold sm:grid-cols-4">{["BRIEF","CREATE","BRAND QA","HANDOFF"].map((x,i)=><div key={x} className="flex items-center gap-2"><span className="grid size-7 place-items-center rounded-full bg-[#F5B800]">{i+1}</span>{x}</div>)}</div><div className="mt-8 border-t border-black/10 pt-6"><p className="font-mono text-xs text-black/55">NOMMAGE RECOMMANDÉ</p><code className="mt-2 block overflow-auto rounded-lg bg-[#111111] p-4 text-sm text-[#F5B800]">AC_WEBINAR_ARTCI_announcement_1080x1350_FR_v03.png</code></div></div><p className="mt-8 max-w-2xl text-sm leading-6 text-black/55">DRAFT → REVIEW → APPROVED → PUBLISHED → ARCHIVED. Toute solution récurrente validée revient dans le système sous forme de règle, token, composant ou template.</p></section>
<footer className="bg-[#F5B800] px-5 py-10 md:px-12"><b className="text-2xl">AfroCodeurs</b><p className="mt-2 text-sm">Des problèmes aux solutions, ensemble.</p><p className="mt-6 font-mono text-[10px] uppercase tracking-widest">Brand Hub · version {b.version} · Source de vérité</p></footer>
</main></div></div>}
function Eyebrow({children,icon:Icon}:{children:React.ReactNode;icon:typeof Palette}){return <p className="flex items-center gap-2 font-mono text-xs font-bold uppercase tracking-[.18em] opacity-55"><Icon className="size-4"/>{children}</p>}
function Title({children}:{children:React.ReactNode}){return <h2 className="mt-4 max-w-3xl text-3xl font-black tracking-[-.035em] md:text-5xl">{children}</h2>}
function Card({children}:{children:React.ReactNode}){return <div className="rounded-xl border border-black/10 bg-white p-6 md:p-8">{children}</div>}
function Rule({title,items,good=false}:{title:string;items:string[];good?:boolean}){return <div className={"rounded-xl border p-6 "+(good?"border-[#22C55E]/30 bg-[#22C55E]/10":"border-red-600/25 bg-red-600/5")}><b className="text-lg">{title}</b><ul className="mt-5 space-y-3 text-sm">{items.map(x=><li key={x}>{x}</li>)}</ul></div>}
