CREATE TABLE "BrandSettings" (
  "id" TEXT NOT NULL DEFAULT 'main',
  "version" TEXT NOT NULL DEFAULT '1.0',
  "tagline" TEXT NOT NULL DEFAULT 'Des problèmes aux solutions, ensemble.',
  "mantra" TEXT NOT NULL DEFAULT 'Build Before Consume.',
  "intro" TEXT NOT NULL DEFAULT 'Une identité panafricaine contemporaine pour celles et ceux qui construisent.',
  "gold" TEXT NOT NULL DEFAULT '#F5B800',
  "black" TEXT NOT NULL DEFAULT '#111111',
  "green" TEXT NOT NULL DEFAULT '#22C55E',
  "ivory" TEXT NOT NULL DEFAULT '#FAFAF8',
  "night" TEXT NOT NULL DEFAULT '#0D0C0A',
  "stone" TEXT NOT NULL DEFAULT '#5C5C54',
  "visualPrinciple" TEXT NOT NULL DEFAULT 'Signal + Structure + Humain',
  "visualGuidance" TEXT NOT NULL DEFAULT 'Grilles, blocs, lignes, nœuds, code et personnes réelles. Les références africaines doivent avoir du sens, jamais servir de remplissage folklorique.',
  "graphicGuidance" TEXT NOT NULL DEFAULT 'Grille, hiérarchie, photo, illustration, exports et fichiers sources.',
  "motionGuidance" TEXT NOT NULL DEFAULT 'Mouvement, lower thirds, transitions, titres, sous-titres et safe areas.',
  "devGuidance" TEXT NOT NULL DEFAULT 'Tokens, composants, accessibilité, responsive, dark mode et reduced motion.',
  "socialGuidance" TEXT NOT NULL DEFAULT 'Déclinaisons par canal, lisibilité mobile, CTA, alt text et campagne.',
  "webinarLabel" TEXT NOT NULL DEFAULT 'WEBINAR #01',
  "webinarTitle" TEXT NOT NULL DEFAULT E'COMPRENDRE.\nCONSTRUIRE.\nPARTAGER.',
  "webinarMeta" TEXT NOT NULL DEFAULT '15 OCT · 18:30 GMT · EN LIGNE',
  "figmaUrl" TEXT,
  "canvaUrl" TEXT,
  "assetsUrl" TEXT,
  "updatedById" TEXT,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "BrandSettings_pkey" PRIMARY KEY ("id")
);
INSERT INTO "BrandSettings" ("id") VALUES ('main') ON CONFLICT ("id") DO NOTHING;
