"use client";
import { useActionState, useState } from "react";
import { Button } from "@/components/ui/button";
import { createEventAction } from "./actions";
import { EVENT_FORMATS, EVENT_FORMAT_LABELS, EVENT_TYPES, EVENT_TYPE_LABELS } from "./constants";
const field = "rounded-md border border-border bg-background px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-primary";
export function EventForm({ communities }: { communities: Array<{ id: string; name: string }> }) {
  const [state, action, pending] = useActionState(createEventAction, undefined); const [format, setFormat] = useState<(typeof EVENT_FORMATS)[number]>("ONLINE");
  return <form action={action} className="grid gap-5"><label className="grid gap-1 text-sm font-medium">Titre<input className={field} name="title" required /></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm font-medium">Type<select className={field} name="type">{EVENT_TYPES.map(x => <option key={x} value={x}>{EVENT_TYPE_LABELS[x]}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">Format<select className={field} name="format" value={format} onChange={e => setFormat(e.target.value as typeof format)}>{EVENT_FORMATS.map(x => <option key={x} value={x}>{EVENT_FORMAT_LABELS[x]}</option>)}</select></label></div><label className="grid gap-1 text-sm font-medium">Résumé<textarea className={field} name="summary" rows={3} required /></label><label className="grid gap-1 text-sm font-medium">Description<textarea className={field} name="description" rows={8} required /></label><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm font-medium">Début<input className={field} name="startsAt" type="datetime-local" required /></label><label className="grid gap-1 text-sm font-medium">Fin<input className={field} name="endsAt" type="datetime-local" required /></label></div><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm font-medium">Fuseau horaire<input className={field} name="timezone" defaultValue="Africa/Abidjan" required /></label><label className="grid gap-1 text-sm font-medium">Places disponibles<input className={field} name="capacity" type="number" min="1" placeholder="Illimité" /></label></div>{format !== "IN_PERSON" && <div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm font-medium">Plateforme<input className={field} name="platform" placeholder="Jitsi, YouTube Live…" /></label><label className="grid gap-1 text-sm font-medium">Lien privé du direct<input className={field} name="accessUrl" type="url" required /></label></div>}{format !== "ONLINE" && <div className="grid gap-4 sm:grid-cols-3"><label className="grid gap-1 text-sm font-medium">Lieu<input className={field} name="venue" required /></label><label className="grid gap-1 text-sm font-medium">Ville<input className={field} name="city" /></label><label className="grid gap-1 text-sm font-medium">Pays<input className={field} name="country" /></label></div>}<label className="grid gap-1 text-sm font-medium">Communauté associée<select className={field} name="communityId"><option value="">Aucune — événement général</option>{communities.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{state?.error && <p className="text-sm text-destructive">{state.error}</p>}<Button disabled={pending} className="justify-self-start">{pending ? "Publication…" : "Publier l’événement"}</Button></form>;
}
